In [31]:
from mxnet import nd

In [32]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [33]:
x.shape

(12,)

In [34]:
x.size

12

In [37]:
X = x.reshape((3, 4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [38]:
nd.zeros((2, 3, 4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [39]:
nd.ones((3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [40]:
Y = nd.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [41]:
Y


[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
<NDArray 3x4 @cpu(0)>

In [42]:
nd.random.normal(0, 1, shape=(3, 4))


[[-0.68106437 -0.13531584  0.37723127  0.41016445]
 [ 0.5712682  -2.7579627   1.07628    -0.6141326 ]
 [ 1.8307649  -1.1468065   0.05383795 -2.5074806 ]]
<NDArray 3x4 @cpu(0)>

In [43]:
X == Y


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [44]:
X + Y


[[ 1.  3.  5.  7.]
 [ 9. 11. 13. 15.]
 [17. 19. 21. 23.]]
<NDArray 3x4 @cpu(0)>

In [45]:
X * Y


[[  0.   2.   6.  12.]
 [ 20.  30.  42.  56.]
 [ 72.  90. 110. 132.]]
<NDArray 3x4 @cpu(0)>

In [46]:
X / Y


[[0.         0.5        0.6666667  0.75      ]
 [0.8        0.8333333  0.85714287 0.875     ]
 [0.8888889  0.9        0.90909094 0.9166667 ]]
<NDArray 3x4 @cpu(0)>

In [47]:
Y.exp()


[[2.7182817e+00 7.3890562e+00 2.0085537e+01 5.4598148e+01]
 [1.4841316e+02 4.0342880e+02 1.0966332e+03 2.9809580e+03]
 [8.1030840e+03 2.2026465e+04 5.9874141e+04 1.6275480e+05]]
<NDArray 3x4 @cpu(0)>

In [48]:
nd.dot(X, Y.T)


[[ 20.  44.  68.]
 [ 60. 148. 236.]
 [100. 252. 404.]]
<NDArray 3x3 @cpu(0)>

In [49]:
X, Y

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 3x4 @cpu(0)>, 
 [[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]
 <NDArray 3x4 @cpu(0)>)

In [50]:
nd.concat(X, Y, dim=0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
<NDArray 6x4 @cpu(0)>

In [51]:
nd.concat(X, Y, dim=1)


[[ 0.  1.  2.  3.  1.  2.  3.  4.]
 [ 4.  5.  6.  7.  5.  6.  7.  8.]
 [ 8.  9. 10. 11.  9. 10. 11. 12.]]
<NDArray 3x8 @cpu(0)>

In [52]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

In [53]:
X.norm().asscalar()

22.494442

In [55]:
A = nd.arange(3).reshape((3, 1))
B = nd.arange(2).reshape((1, 2))
A, B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [56]:
A + B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [57]:
X[1: 3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [59]:
import numpy as np
P = np.ones((2, 3))
D = nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [60]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)